# Generated by Django 3.0.8 on 2020-07-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cjoice',
            new_name='Choice',
        ),
    ]
